INFO:root:Racing: 'student'
INFO:root:Starting TORCS...
INFO:root:Starting players...
ERROR:root:An error occurred, trying to stop gracefully...
INFO:root:Terminating psutil.Popen(pid=14424, name='python3')
INFO:root:Closed all files and processes!
Traceback (most recent call last):
  File "./torcs_tournament.py", line 1039, in <module>
    controller.race_and_save(simulate=args.simulate)
  File "./torcs_tournament.py", line 394, in race_and_save
    self.race(simulate=simulate)
  File "./torcs_tournament.py", line 409, in race
    self.race_once(players, simulate=simulate)
  File "./torcs_tournament.py", line 907, in race_once
    **kwargs
  File "./torcs_tournament.py", line 558, in race_once
    list(proc.args) or name
subprocess.CalledProcessError: Command '['torcs', '-r', '/home/student/Documents/CI/ToxicRacing/quickrace.xml']' returned non-zero exit status 0
2017-11-10 13:12:04,250    INFO pytocl.protocol Registering driver client with server ('localhost', 3001).
2017-11-10 13:12:04,250    INFO pytocl.protocol Registering client.
