2017-11-09 17:20:13,840    INFO pytocl.protocol Registering driver client with server ('localhost', 3001).
2017-11-09 17:20:13,841    INFO pytocl.protocol Registering client.
2017-11-09 17:20:13,846    INFO pytocl.protocol Connection successful.
2017-11-09 17:20:14,144    INFO pytocl.protocol Disconnecting from racing server.
2017-11-09 17:20:14,145    INFO pytocl.protocol Client stopped.
2017-11-09 17:20:14,146    INFO pytocl.protocol Registering driver client with server ('localhost', 3001).
2017-11-09 17:20:14,146    INFO pytocl.protocol Registering client.
2017-11-09 17:34:00,492    INFO pytocl.protocol Connection successful.
2017-11-09 17:34:00,718    INFO pytocl.protocol Disconnecting from racing server.
2017-11-09 17:34:00,718    INFO pytocl.protocol Client stopped.
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
